[package]
name = "mc2-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mc2-core.workspace = true
mc2-gpu.workspace = true
mc2-voxel.workspace = true
wgpu.workspace = true
bytemuck.workspace = true
glam.workspace = true
font8x8.workspace = true
png.workspace = true
log.workspace = true

[dev-dependencies]
mc2-worldgen.workspace = true
naga = { version = "30.0.1", features = ["wgsl-in", "hlsl-out"] }
